OPENEUROPA-3048: Use the sparql_entity_storage module.
openeuropa/rdf_skos pull request #49
Opened 2020-07-02 16:03 UTC by imanoleguskiza

2020-09-22 16:08 UTC, sergepavle reviewed
I have left some question in PR.
Everything else looks good.

2020-09-22 16:08 UTC, sergepavle commented on README.md
> +1. Require `drupal/rdf_entity` with the new `1.0-alpha17` version and `drupal/rdf_skos` with the new `0.8.0` version.
0.8.0 version or 0.9.0?

2020-09-22 16:51 UTC, sergepavle commented on composer.json
> +        "drupal/sparql_entity_storage": "^1.0.0-alpha5",
I have found that in the ewcms we already have enabled module (empty one). So looks like this PR related to second stage of deployments.

2020-10-19 08:47 UTC, sergepavle commented on README.md
> +1. Remove the empty `drupal/sparql_entity_storage` module requirement
```suggestion
1. Remove the empty `drupal/sparql_entity_storage` module requirement.
```

2020-10-19 08:58 UTC, sergepavle submitted a review, later dismissed

2020-10-19 11:04 UTC, nagyad requested changes

2020-10-20 09:27 UTC, nagyad approved these changes

2021-01-20 08:28 UTC, brummbar requested changes

2021-01-20 08:28 UTC, brummbar commented on composer.json
> +        "drupal/sparql_entity_storage": "^1.0.0-alpha6",
There's alpha8 now out, let's move to that.

2021-02-02 15:21 UTC, brummbar submitted a review, later dismissed

2021-02-03 09:40 UTC, brummbar approved these changes

2021-02-03 10:07 UTC, brummbar submitted a review, later dismissed

2021-02-03 10:44 UTC, ademarco approved these changes

2021-02-03 12:48 UTC, brummbar approved these changes

2021-02-03 12:49 UTC, merged