EWPP-929: Drupal 9 compatibility fixes.
openeuropa/rdf_skos pull request #69
Opened 2021-04-16 12:33 UTC by yenyasinn

2021-04-20 08:15 UTC, yenyasinn commented on phpunit.xml.dist
> +    <testsuite name="unit_tests">
We have to provide some name here.

2021-04-20 11:44 UTC, ademarco requested changes

2021-04-20 11:44 UTC, ademarco commented on composer.json
> +        "openeuropa/drupal-core-require-dev": "^8.9.13 || ^9.1.6",
This needs to be the same as what's in `"require"`, we let composer resolve versions.
```suggestion
        "openeuropa/drupal-core-require-dev": "^8.9 || ^9",
```

2021-04-20 11:44 UTC, ademarco commented on composer.json
> +        "drupal/core": "^8.9 || ^9.1",
As we cannot be sure that our sites can be updated from 8.9 to 9.1 directly, without passing by 9.0, we have to make sure that a component will not add such a constraint, unless it is actually needed.

Please use here:

```suggestion
        "drupal/core": "^8.9 || ^9",
```

2021-04-20 11:44 UTC, ademarco commented on tests/modules/rdf_skos_test/rdf_skos_test.info.yml
> +core_version_requirement: ^8.9 || ^9.1
```suggestion
core_version_requirement: ^8.9 || ^9
```

2021-04-20 13:21 UTC, imanoleguskiza submitted a review, later dismissed

2021-04-21 13:28 UTC, ademarco approved these changes, later dismissed

2021-04-23 08:23 UTC, upchuk approved these changes

2021-04-23 08:34 UTC, ademarco approved these changes

2021-04-23 08:35 UTC, merged