EWPP-2994: Drupal 10 compatibility.
openeuropa/rdf_skos pull request #89
Opened 2023-02-10 23:44 UTC by brummbar

2023-02-20 14:06 UTC, drishu approved these changes, later dismissed

2023-03-10 14:48 UTC, sergepavle requested changes

2023-03-10 14:48 UTC, sergepavle commented on composer.json
>              "Replacing abandoned easyrdf/easyrdf library with the sweetrdf/easyrdf fork compatible with PHP 8.1",
It is removed already.

2023-03-13 13:30 UTC, sergepavle approved these changes

2023-03-13 13:34 UTC, drishu approved these changes

2023-03-13 14:53 UTC, merged